var chai = global.chai = require('chai');
var expect = global.expect = require('chai').expect;
var Promise = require('es6-promise').Promise;
global.Promise = Promise;
var jsdom = require('jsdom');
var doc = jsdom.jsdom("<html><body></body></html>");
var win = doc.defaultView;
global.document = doc;
global.window = win;
global.navigator = win.navigator;
