language: node_js
node_js:
  - "4"
  - "5"
branches:
  only:
    - master
sudo: false
script: "npm run test:cov"
addons:
  code_climate:
    repo_token: 022cc1eb41ae58f6a6d99f7935a3703489e28be9e680996e13c363b2377573a7
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
